/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as unauthenticatedRouteRouteImport } from './routes/(unauthenticated)/route'
import { Route as authenthicatedRouteRouteImport } from './routes/(authenthicated)/route'
import { Route as authenthicatedIndexRouteImport } from './routes/(authenthicated)/index'
import { Route as authenthicatedTransactionsRouteImport } from './routes/(authenthicated)/transactions'
import { Route as authenthicatedProfileRouteImport } from './routes/(authenthicated)/profile'
import { Route as authenthicatedSlotsIndexRouteImport } from './routes/(authenthicated)/slots/index'
import { Route as unauthenticatedauthRegisterRouteImport } from './routes/(unauthenticated)/(auth)/register'
import { Route as unauthenticatedauthLoginRouteImport } from './routes/(unauthenticated)/(auth)/login'
import { Route as authenthicatedSlotsIdRouteImport } from './routes/(authenthicated)/slots/$id'

const unauthenticatedRouteRoute = unauthenticatedRouteRouteImport.update({
  id: '/(unauthenticated)',
  getParentRoute: () => rootRouteImport,
} as any)
const authenthicatedRouteRoute = authenthicatedRouteRouteImport.update({
  id: '/(authenthicated)',
  getParentRoute: () => rootRouteImport,
} as any)
const authenthicatedIndexRoute = authenthicatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => authenthicatedRouteRoute,
} as any)
const authenthicatedTransactionsRoute =
  authenthicatedTransactionsRouteImport.update({
    id: '/transactions',
    path: '/transactions',
    getParentRoute: () => authenthicatedRouteRoute,
  } as any)
const authenthicatedProfileRoute = authenthicatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => authenthicatedRouteRoute,
} as any)
const authenthicatedSlotsIndexRoute =
  authenthicatedSlotsIndexRouteImport.update({
    id: '/slots/',
    path: '/slots/',
    getParentRoute: () => authenthicatedRouteRoute,
  } as any)
const unauthenticatedauthRegisterRoute =
  unauthenticatedauthRegisterRouteImport.update({
    id: '/(auth)/register',
    path: '/register',
    getParentRoute: () => unauthenticatedRouteRoute,
  } as any)
const unauthenticatedauthLoginRoute =
  unauthenticatedauthLoginRouteImport.update({
    id: '/(auth)/login',
    path: '/login',
    getParentRoute: () => unauthenticatedRouteRoute,
  } as any)
const authenthicatedSlotsIdRoute = authenthicatedSlotsIdRouteImport.update({
  id: '/slots/$id',
  path: '/slots/$id',
  getParentRoute: () => authenthicatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/profile': typeof authenthicatedProfileRoute
  '/transactions': typeof authenthicatedTransactionsRoute
  '/': typeof authenthicatedIndexRoute
  '/slots/$id': typeof authenthicatedSlotsIdRoute
  '/login': typeof unauthenticatedauthLoginRoute
  '/register': typeof unauthenticatedauthRegisterRoute
  '/slots/': typeof authenthicatedSlotsIndexRoute
}
export interface FileRoutesByTo {
  '/profile': typeof authenthicatedProfileRoute
  '/transactions': typeof authenthicatedTransactionsRoute
  '/': typeof authenthicatedIndexRoute
  '/slots/$id': typeof authenthicatedSlotsIdRoute
  '/login': typeof unauthenticatedauthLoginRoute
  '/register': typeof unauthenticatedauthRegisterRoute
  '/slots': typeof authenthicatedSlotsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(authenthicated)': typeof authenthicatedRouteRouteWithChildren
  '/(unauthenticated)': typeof unauthenticatedRouteRouteWithChildren
  '/(authenthicated)/profile': typeof authenthicatedProfileRoute
  '/(authenthicated)/transactions': typeof authenthicatedTransactionsRoute
  '/(authenthicated)/': typeof authenthicatedIndexRoute
  '/(authenthicated)/slots/$id': typeof authenthicatedSlotsIdRoute
  '/(unauthenticated)/(auth)/login': typeof unauthenticatedauthLoginRoute
  '/(unauthenticated)/(auth)/register': typeof unauthenticatedauthRegisterRoute
  '/(authenthicated)/slots/': typeof authenthicatedSlotsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/profile'
    | '/transactions'
    | '/'
    | '/slots/$id'
    | '/login'
    | '/register'
    | '/slots/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/profile'
    | '/transactions'
    | '/'
    | '/slots/$id'
    | '/login'
    | '/register'
    | '/slots'
  id:
    | '__root__'
    | '/(authenthicated)'
    | '/(unauthenticated)'
    | '/(authenthicated)/profile'
    | '/(authenthicated)/transactions'
    | '/(authenthicated)/'
    | '/(authenthicated)/slots/$id'
    | '/(unauthenticated)/(auth)/login'
    | '/(unauthenticated)/(auth)/register'
    | '/(authenthicated)/slots/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  authenthicatedRouteRoute: typeof authenthicatedRouteRouteWithChildren
  unauthenticatedRouteRoute: typeof unauthenticatedRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(unauthenticated)': {
      id: '/(unauthenticated)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof unauthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(authenthicated)': {
      id: '/(authenthicated)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authenthicatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(authenthicated)/': {
      id: '/(authenthicated)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof authenthicatedIndexRouteImport
      parentRoute: typeof authenthicatedRouteRoute
    }
    '/(authenthicated)/transactions': {
      id: '/(authenthicated)/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof authenthicatedTransactionsRouteImport
      parentRoute: typeof authenthicatedRouteRoute
    }
    '/(authenthicated)/profile': {
      id: '/(authenthicated)/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof authenthicatedProfileRouteImport
      parentRoute: typeof authenthicatedRouteRoute
    }
    '/(authenthicated)/slots/': {
      id: '/(authenthicated)/slots/'
      path: '/slots'
      fullPath: '/slots/'
      preLoaderRoute: typeof authenthicatedSlotsIndexRouteImport
      parentRoute: typeof authenthicatedRouteRoute
    }
    '/(unauthenticated)/(auth)/register': {
      id: '/(unauthenticated)/(auth)/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof unauthenticatedauthRegisterRouteImport
      parentRoute: typeof unauthenticatedRouteRoute
    }
    '/(unauthenticated)/(auth)/login': {
      id: '/(unauthenticated)/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof unauthenticatedauthLoginRouteImport
      parentRoute: typeof unauthenticatedRouteRoute
    }
    '/(authenthicated)/slots/$id': {
      id: '/(authenthicated)/slots/$id'
      path: '/slots/$id'
      fullPath: '/slots/$id'
      preLoaderRoute: typeof authenthicatedSlotsIdRouteImport
      parentRoute: typeof authenthicatedRouteRoute
    }
  }
}

interface authenthicatedRouteRouteChildren {
  authenthicatedProfileRoute: typeof authenthicatedProfileRoute
  authenthicatedTransactionsRoute: typeof authenthicatedTransactionsRoute
  authenthicatedIndexRoute: typeof authenthicatedIndexRoute
  authenthicatedSlotsIdRoute: typeof authenthicatedSlotsIdRoute
  authenthicatedSlotsIndexRoute: typeof authenthicatedSlotsIndexRoute
}

const authenthicatedRouteRouteChildren: authenthicatedRouteRouteChildren = {
  authenthicatedProfileRoute: authenthicatedProfileRoute,
  authenthicatedTransactionsRoute: authenthicatedTransactionsRoute,
  authenthicatedIndexRoute: authenthicatedIndexRoute,
  authenthicatedSlotsIdRoute: authenthicatedSlotsIdRoute,
  authenthicatedSlotsIndexRoute: authenthicatedSlotsIndexRoute,
}

const authenthicatedRouteRouteWithChildren =
  authenthicatedRouteRoute._addFileChildren(authenthicatedRouteRouteChildren)

interface unauthenticatedRouteRouteChildren {
  unauthenticatedauthLoginRoute: typeof unauthenticatedauthLoginRoute
  unauthenticatedauthRegisterRoute: typeof unauthenticatedauthRegisterRoute
}

const unauthenticatedRouteRouteChildren: unauthenticatedRouteRouteChildren = {
  unauthenticatedauthLoginRoute: unauthenticatedauthLoginRoute,
  unauthenticatedauthRegisterRoute: unauthenticatedauthRegisterRoute,
}

const unauthenticatedRouteRouteWithChildren =
  unauthenticatedRouteRoute._addFileChildren(unauthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  authenthicatedRouteRoute: authenthicatedRouteRouteWithChildren,
  unauthenticatedRouteRoute: unauthenticatedRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
